name: 'Terraform Deploy'

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Umožní manuálne spustenie workflow

# Jednoduchší workflow bez použitia artefaktov
jobs:
  validate:
    name: 'Validácia'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    - name: Terraform Format Check
      run: terraform fmt -check
      continue-on-error: true

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate

  plan:
    name: 'Plánovanie'
    needs: validate
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan
      # Odstránené ukladanie plánu ako artefaktu

  apply:
    name: 'Nasadenie'
    needs: plan
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    defaults:
      run:
        working-directory: ./terraform
    environment: production  # Voliteľný krok pre schválenie nasadenia
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      run: terraform apply -auto-approve
      # Použitie priameho apply bez použitia plánu z predchádzajúceho kroku
      
    - name: Notify Slack about deployment status
      # Tu môžete pridať krok pre notifikáciu do Slacku alebo iného systému
      run: echo "Infraštruktúra bola úspešne nasadená"